
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * 将前端错误写入统一 tracing 日志流（AI 修 bug 的输入就是这份日志）。
 */
async logFrontendError(payload: FrontendErrorPayload) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("log_frontend_error", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 返回应用当前版本（取自 tauri.conf 的 package 版本，与 updater 比对同源，随发布 tag 同步）。
 * 前端页脚/设置页展示真实版本，避免硬编码漂移；「是否有新版」由 updater 域另行驱动。
 */
async appVersion() : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("app_version") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<Result<Settings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSettings(patch: SettingsPatch) : Promise<Result<Settings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_settings", { patch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 选择输出根目录（返回所选路径；取消返回 None）。
 */
async pickOutputDir() : Promise<Result<string | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pick_output_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 选择单个 .txt 文件（提示词导入）。
 */
async pickTxtFile() : Promise<Result<string | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pick_txt_file") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 选择多张图片（参考图上传）。
 */
async pickImageFiles() : Promise<Result<string[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pick_image_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 在系统文件管理器中打开日志目录。
 */
async openLogsDir() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_logs_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 在系统文件管理器中显示指定路径（打开所在文件夹）。
 */
async openPathInFolder(path: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_path_in_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listApiKeys() : Promise<Result<ApiKeyView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_api_keys") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addApiKey(input: AddApiKeyInput) : Promise<Result<ApiKeyView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_api_key", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateApiKey(id: number, patch: UpdateApiKeyPatch) : Promise<Result<ApiKeyView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_api_key", { id, patch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setApiKeyEnabled(id: number, enabled: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_api_key_enabled", { id, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteApiKey(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_api_key", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 导入参考图：拷入库、生成缩略图、写记录，返回视图列表。
 */
async importRefImages(paths: string[], groupId: number | null) : Promise<Result<RefImageView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_ref_images", { paths, groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 列出全部未删除参考图（供参考图库/生成页选择）。
 */
async listRefImages() : Promise<Result<RefImageView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_ref_images") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 调整参考图分组。
 */
async setRefImageGroup(id: number, groupId: number | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_ref_image_group", { id, groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRefImage(id: number) : Promise<Result<RefImageDetail, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_ref_image", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 更换参考图文件（保留 id 与关联）。
 */
async replaceRefImageFile(id: number, path: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("replace_ref_image_file", { id, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除参考图 → 进废纸篓。
 */
async trashRefImage(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trash_ref_image", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 列出全部提示词分组（含 active 提示词数）。
 */
async listPromptGroups() : Promise<Result<GroupView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_prompt_groups") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 新建正式分组（E30a 参考图导入选组 /「新建分组」；E20 分组管理复用）。
 * 自动从分组名生成唯一前缀（号池按前缀发放）。
 */
async createPromptGroup(name: string) : Promise<Result<GroupView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_prompt_group", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listPrompts(groupId: number) : Promise<Result<PromptView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_prompts", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchPrompts(query: string) : Promise<Result<PromptView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_prompts", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPrompt(id: number) : Promise<Result<PromptView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePromptText(id: number, text: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_prompt_text", { id, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async togglePromptFavorite(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_prompt_favorite", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除提示词 → 进废纸篓（编号在清理时回收）。
 */
async trashPrompt(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trash_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 第一步：解析 txt，构建预览（不落库）。
 */
async parsePromptTxt(path: string) : Promise<Result<ImportPreview, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("parse_prompt_txt", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 第二步：落库（ctx=generate 时建临时分组）。号池发放与写入同事务。
 */
async commitPromptImport(preview: ImportPreview, ctx: string) : Promise<Result<ImportResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("commit_prompt_import", { preview, ctx }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 组合展开创建批次，调度器自动开跑。返回批次视图（含任务总数）。
 */
async createBatch(input: CreateBatchInput) : Promise<Result<BatchView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_batch", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 历史单张生成均值秒数（E31 确认摘要 ETA 估算）；无成功历史返回 None。
 */
async estimateTaskSeconds() : Promise<Result<number | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("estimate_task_seconds") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 取消批次剩余排队任务（E03）：删除该批次全部 'q' 态任务，重估归档并补发汇总。
 * 在途（run/retry）任务不受影响，会自行跑完。返回取消数。
 */
async cancelBatchPending(batchId: number) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_batch_pending", { batchId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listBatches() : Promise<Result<BatchView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_batches") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pauseQueue() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_queue") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resumeQueue() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_queue") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 列出某批次任务，可按 5 视觉组筛选：all/pending/running/failed/review/done。
 */
async listTasks(batchId: number, statusGroup: string | null, page: number | null) : Promise<Result<TaskView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_tasks", { batchId, statusGroup, page }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTask(id: number) : Promise<Result<TaskView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_task", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 手动重试单个失败任务（可携带微调提示词写入快照，R8）。
 */
async retryTask(id: number, editedPrompt: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retry_task", { id, editedPrompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 重试某批次全部失败任务。
 */
async retryFailedTasks(batchId: number) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retry_failed_tasks", { batchId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除单个任务（「不需要了」）。生成中/重试中的任务不允许删除，避免与在途 worker 竞争；
 * 删除会级联清除 task_attempts（外键 ON DELETE CASCADE）。删除后重估批次归档并补发汇总。
 */
async deleteTask(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_task", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除某批次全部失败任务（批量「不需要了」）。返回删除数。
 */
async deleteFailedTasks(batchId: number) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_failed_tasks", { batchId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 重试全部因中断而失败的任务（error_type=Interrupted）。
 */
async retryInterruptedTasks() : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retry_interrupted_tasks") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 统计当前中断任务数（前端 banner 用）。
 */
async countInterrupted() : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("count_interrupted") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listPendingReview(batchId: number | null) : Promise<Result<ReviewItemView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_pending_review", { batchId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 通过所选：输出原图 + 写作品快照 + 微调写回(R8) + 临时组转正(R7)，单事务。
 */
async acceptTasks(taskIds: number[]) : Promise<Result<AcceptResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("accept_tasks", { taskIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 不通过所选：置 rej + 原图暂存进废纸篓（E02，不立即物理删除）+ 留缩略图，单事务。
 */
async rejectTasks(taskIds: number[]) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reject_tasks", { taskIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listWorks(filter: WorkFilter, page: number | null) : Promise<Result<WorkView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_works", { filter, page }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWork(id: number) : Promise<Result<WorkView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_work", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleWorkFavorite(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_work_favorite", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除作品 → 进废纸篓（记录删除，文件待清理时物理删）。
 */
async trashWork(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trash_work", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listTrash() : Promise<Result<TrashItemView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_trash") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async purgeTrashItems(ids: number[]) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("purge_trash_items", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async purgeAllTrash() : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("purge_all_trash") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async countTrash() : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("count_trash") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 手动/启动检查更新：有新版则后台下载并暂存，emit ready。
 */
async checkUpdateNow() : Promise<Result<string | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_update_now") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 安装已下载的更新并重启（用户确认「重启安装」时调用）。
 */
async installUpdate() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dataDirInfo() : Promise<Result<DataDirInfo, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("data_dir_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 在系统文件管理器中打开数据目录。
 */
async openDataDir() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_data_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 导出备份：选目标 zip → WAL 检查点 → 打包数据目录（排除 logs）。
 * 队列运行中（有 run/retry 任务）拒绝，避免边写边打包出不一致备份。
 * 返回所选路径；用户取消返回 None。
 */
async exportBackup() : Promise<Result<string | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_backup") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
backupProgress: BackupProgress,
batchSummary: BatchSummary,
keyHealth: KeyHealth,
taskProgress: TaskProgress,
taskStatusChanged: TaskStatusChanged,
updateStateChanged: UpdateStateChanged
}>({
backupProgress: "backup-progress",
batchSummary: "batch-summary",
keyHealth: "key-health",
taskProgress: "task-progress",
taskStatusChanged: "task-status-changed",
updateStateChanged: "update-state-changed"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * 验收结果。
 */
export type AcceptResult = { accepted: number; 
/**
 * 本次因验收通过而转正的临时分组名（前端 toast）
 */
promotedGroups: string[] }
export type AddApiKeyInput = { alias: string; key: string; baseUrl: string; model: string; concurrencyLimit: number }
/**
 * API Key 脱敏视图（Key 本体永不出 Rust）。
 */
export type ApiKeyView = { id: number; name: string; 
/**
 * 脱敏 Key：`****后4位`
 */
maskedKey: string; baseUrl: string; model: string; concurrencyLimit: number; enabled: boolean; 
/**
 * 近 50 次成功率（0.0–1.0）
 */
successRate: number; 
/**
 * 成功率样本量
 */
sampleCount: number; 
/**
 * 当前占用并发（运行时；M2 引擎接入后填充，M1 恒为 0）
 */
usedConcurrency: number }
/**
 * 应用级错误。`type` 字段作为前端可判别的分类标签。
 */
export type AppError = 
/**
 * 数据库 / 持久化失败。
 */
{ type: "Database"; message: string } | 
/**
 * 文件系统 / IO 失败。
 */
{ type: "Io"; message: string } | 
/**
 * 输入参数非法（前端应在提交前拦截，此为兜底）。
 */
{ type: "InvalidInput"; message: string } | 
/**
 * 系统钥匙串（Keychain / 凭据管理器）访问失败。
 */
{ type: "Keyring"; message: string } | 
/**
 * 其它未分类错误。
 */
{ type: "Internal"; message: string }
/**
 * `backup://progress`：导出进度（前端进度条）。
 */
export type BackupProgress = { done: number; total: number; 
/**
 * running / done / error
 */
phase: string }
/**
 * `batch://summary`（250ms 节流）
 */
export type BatchSummary = { batchId: number; counts: SummaryCounts; activeConcurrency: number; paused: boolean }
export type BatchView = { id: number; createdAt: number; status: string; taskCount: number; 
/**
 * 批次生效的生成参数快照（E16 / D1），任务页可回查。
 */
paramsJson: string }
export type CreateBatchInput = { refs: RefMappingInput[]; paramsJson: string; 
/**
 * 抽卡次数 k（E17 / D2）：每个组合独立生成 k 次。默认 1，后端夹取 1..=5。
 */
draws: number }
/**
 * 数据目录信息（E19：暴露落盘位置）。
 */
export type DataDirInfo = { root: string; dbPath: string }
/**
 * 六类错误（落 `tasks.error_type` / `task_attempts.error_type`）。
 */
export type ErrorType = "Timeout" | "RateLimited" | "ContentPolicy" | "Auth" | "Interrupted" | "Other"
/**
 * 前端未捕获错误载荷。经 ErrorBoundary / window.onerror 采集后转发到此。
 */
export type FrontendErrorPayload = { 
/**
 * 错误消息。
 */
message: string; 
/**
 * 调用栈（可选）。
 */
stack: string | null; 
/**
 * 来源标识（组件 / 路由）。
 */
source: string | null; 
/**
 * 关联任务 ID（若发生在任务上下文），用于全链路贯穿。
 */
taskId: string | null }
/**
 * 分组视图（生成页 / 提示词库列表）。
 */
export type GroupView = { id: number; name: string; prefix: string; scene: string; isTemp: boolean; count: number }
/**
 * 导入预览（parse 阶段产物，不落库）。
 */
export type ImportPreview = { encoding: string; groups: ImportPreviewGroup[]; total: number }
export type ImportPreviewGroup = { name: string; prefix: string; scene: string; tags: string[]; count: number; 
/**
 * 预分配编号区间预览，如 "DZ-0001 ~ DZ-0024"（忽略回收池，仅供参考）
 */
codeRange: string; isNewGroup: boolean; 
/**
 * 提示词（正文 + 可选小标题；commit 阶段回传落库）
 */
prompts: ImportPreviewPrompt[] }
/**
 * 导入预览中的单条提示词（正文 + 可选小标题）。
 */
export type ImportPreviewPrompt = { title: string | null; text: string }
export type ImportResult = { groupIds: number[]; inserted: number; 
/**
 * 是否新建了临时分组（ctx=generate）
 */
temp: boolean }
/**
 * `keys://health`
 */
export type KeyHealth = { keyId: number; state: KeyState; usedConcurrency: number; successRate: number }
/**
 * Key 健康状态。
 */
export type KeyState = "ok" | "limited" | "auth_failed" | "disabled"
export type Phase = "queued" | "requestStarted" | "generating" | "downloading" | "saved"
/**
 * 提示词视图（编号网格 / 详情）。
 */
export type PromptView = { id: number; groupId: number; code: string; title: string | null; text: string; favorite: boolean; edited: boolean }
/**
 * 参考图详情（含使用统计）。
 */
export type RefImageDetail = { id: number; name: string; groupId: number | null; filePath: string; thumbPath: string; width: number; height: number; usedCount: number; worksCount: number }
export type RefImageView = { id: number; name: string; groupId: number | null; filePath: string; thumbPath: string; width: number; height: number }
export type RefMappingInput = { refImageId: number; promptGroupId: number }
/**
 * 待验收项视图。
 */
export type ReviewItemView = { id: number; batchId: number; refName: string; promptCode: string; groupName: string; keyAlias: string | null; resultImagePath: string | null; resultThumbPath: string | null; promptText: string }
/**
 * 应用设置（单行 JSON 持久化）。
 */
export type Settings = { 
/**
 * 调度策略："round_robin" | "success_rate"
 */
scheduleStrategy: string; 
/**
 * 失败重试次数（0–3）
 */
retryCount: number; 
/**
 * 输出根目录
 */
outputDir: string; 
/**
 * 动效偏好："standard" | "reduced"
 */
motion: string; 
/**
 * 队列暂停态
 */
paused: boolean }
/**
 * 设置补丁（部分更新）。
 */
export type SettingsPatch = { scheduleStrategy: string | null; retryCount: number | null; outputDir: string | null; motion: string | null; paused: boolean | null }
/**
 * 5 视觉组计数。
 */
export type SummaryCounts = { 
/**
 * 待处理 q
 */
pending: number; 
/**
 * 生成中 run+retry
 */
running: number; 
/**
 * 异常 fail
 */
failed: number; 
/**
 * 待验收 rev
 */
review: number; 
/**
 * 已通过 pass
 */
passed: number; 
/**
 * 未通过 rej
 */
rejected: number; total: number }
/**
 * `task://progress`（250ms 节流）
 */
export type TaskProgress = { taskId: number; pct: number; phase: Phase }
export type TaskStatus = 
/**
 * 待生成
 */
"q" | 
/**
 * 生成中
 */
"run" | 
/**
 * 重试中（退避/排队等待再次生成）
 */
"retry" | 
/**
 * 成功（即待验收）
 */
"rev" | 
/**
 * 已通过
 */
"pass" | 
/**
 * 未通过
 */
"rej" | 
/**
 * 失败（可手动重试的终态）
 */
"fail"
/**
 * `task://status-changed`
 */
export type TaskStatusChanged = { taskId: number; batchId: number; status: TaskStatus; errorType: ErrorType | null; errorMessage: string | null; retryCount: number; apiKeyId: number | null }
/**
 * 任务视图（含参考图名/提示词编号/分组名/Key 别名，供任务表直接渲染）。
 */
export type TaskView = { id: number; batchId: number; status: string; refImageId: number; refName: string; promptId: number; promptCode: string; promptTitle: string | null; groupName: string; apiKeyId: number | null; keyAlias: string | null; errorType: string | null; errorMessage: string | null; retryCount: number; resultThumbPath: string | null; promptTextSnapshot: string }
export type TrashItemView = { id: number; entityType: string; code: string | null; title: string | null; refName: string | null; thumbPath: string | null; 
/**
 * 未通过任务的原图路径（E02：原图暂存至清理前可查看）。仅 task 类有值。
 */
imagePath: string | null; promptText: string | null; sourceLabel: string; deletedAt: number }
export type UpdateApiKeyPatch = { name: string | null; baseUrl: string | null; model: string | null; concurrencyLimit: number | null }
/**
 * `update://state`
 */
export type UpdateStateChanged = { 
/**
 * checking / downloading / ready / uptodate / error
 */
state: string; version: string | null }
export type WorkFilter = { groupId: number | null; favoriteOnly: boolean }
export type WorkView = { id: number; promptCode: string; groupName: string; refName: string; batchId: number | null; favorite: number; acceptedAt: number; imagePath: string; thumbPath: string; promptText: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
