
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * 将前端错误写入统一 tracing 日志流（AI 修 bug 的输入就是这份日志）。
 */
async logFrontendError(payload: FrontendErrorPayload) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("log_frontend_error", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 返回应用当前版本（取自 tauri.conf 的 package 版本，与 updater 比对同源，随发布 tag 同步）。
 * 前端页脚/设置页展示真实版本，避免硬编码漂移；「是否有新版」由 updater 域另行驱动。
 */
async appVersion() : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("app_version") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<Result<Settings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSettings(patch: SettingsPatch) : Promise<Result<Settings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_settings", { patch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 选择输出根目录（返回所选路径；取消返回 None）。
 */
async pickOutputDir() : Promise<Result<string | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pick_output_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 选择单个 .txt 文件（提示词导入）。
 */
async pickTxtFile() : Promise<Result<string | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pick_txt_file") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 选择多张图片（参考图上传）。
 */
async pickImageFiles() : Promise<Result<string[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pick_image_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 在系统文件管理器中打开日志目录。
 */
async openLogsDir() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_logs_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 任务5：一键打开图片输出根目录（`outputs/`，各批次/分组子目录都在其下）。
 * 目录不存在（尚无输出）时先创建，避免打开失败。
 */
async openOutputDir() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_output_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 在系统文件管理器中显示指定路径（打开所在文件夹）。
 */
async openPathInFolder(path: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_path_in_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 复制诊断信息（E27）：版本 / OS / Key 数量与状态 / 最近 5 条错误摘要。
 * 明确不含 Key 明文（仅计数与启用/熔断状态），可安全粘贴给支持者。
 */
async diagnosticsInfo() : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("diagnostics_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listApiKeys() : Promise<Result<ApiKeyView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_api_keys") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addApiKey(input: AddApiKeyInput) : Promise<Result<ApiKeyView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_api_key", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateApiKey(id: number, patch: UpdateApiKeyPatch) : Promise<Result<ApiKeyView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_api_key", { id, patch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setApiKeyEnabled(id: number, enabled: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_api_key_enabled", { id, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 恢复被熔断的 Key（E18）：清熔断位 + 重新启用 + 重载调度器。
 */
async recoverApiKey(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("recover_api_key", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteApiKey(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_api_key", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 测试一组连接参数（E11：添加/编辑弹窗，raw key 在前端）。
 */
async testApiKey(baseUrl: string, apiKey: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_api_key", { baseUrl, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 测试已保存的 Key（E11：Key 行内测试，从钥匙串取密钥）。
 */
async testApiKeySaved(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_api_key_saved", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 导入参考图：拷入库、生成缩略图、写记录，返回视图列表。
 */
async importRefImages(paths: string[], groupId: number | null) : Promise<Result<RefImageView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_ref_images", { paths, groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async scanRefImports(paths: string[]) : Promise<Result<RefScanItem[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_ref_imports", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 列出全部未删除参考图（供参考图库/生成页选择）。
 */
async listRefImages() : Promise<Result<RefImageView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_ref_images") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 调整参考图分组。
 */
async setRefImageGroup(id: number, groupId: number | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_ref_image_group", { id, groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 批量改分组（E30b）。gid=None 为未分组。
 */
async setRefImagesGroup(ids: number[], groupId: number | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_ref_images_group", { ids, groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRefImage(id: number) : Promise<Result<RefImageDetail, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_ref_image", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 更换参考图文件（保留 id 与关联）。
 */
async replaceRefImageFile(id: number, path: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("replace_ref_image_file", { id, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除参考图 → 进废纸篓。
 */
async trashRefImage(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trash_ref_image", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 批量删除参考图 → 进废纸篓（E30b）。
 */
async trashRefImages(ids: number[]) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trash_ref_images", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 列出全部提示词分组（含 active 提示词数 + 标签）。
 */
async listPromptGroups() : Promise<Result<GroupView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_prompt_groups") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 新建正式分组（E30a 参考图导入选组 /「新建分组」；E20 分组管理复用）。
 * 自动从分组名生成唯一前缀（号池按前缀发放）。
 */
async createPromptGroup(name: string) : Promise<Result<GroupView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_prompt_group", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 重命名分组（E20，前缀/编号不变）。
 */
async renamePromptGroup(id: number, name: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_prompt_group", { id, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除分组（E20）：组内 active 提示词快照入废纸篓（清理时回收编号），随后删除分组。
 * 关联参考图置为未分组、作品快照保留（accepted_works 无外键级联）。
 */
async deletePromptGroup(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_prompt_group", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 合并分组（E20）：`fromId` 并入 `intoId`，编号前缀保留原值不重编。
 */
async mergePromptGroups(fromId: number, intoId: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("merge_prompt_groups", { fromId, intoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 批量移动提示词到指定分组（E20 单条 / E36 批量；编号前缀保留原值不重编）。
 */
async movePromptsToGroup(ids: number[], groupId: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_prompts_to_group", { ids, groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 批量设置收藏（E36）。favorite=true 收藏，false 取消。
 */
async setPromptsFavorite(ids: number[], favorite: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_prompts_favorite", { ids, favorite }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 批量删除提示词 → 入废纸篓（E36；编号在清理时回收）。
 */
async trashPrompts(ids: number[]) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trash_prompts", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listPrompts(groupId: number) : Promise<Result<PromptView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_prompts", { groupId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchPrompts(query: string) : Promise<Result<PromptView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_prompts", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPrompt(id: number) : Promise<Result<PromptView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePromptText(id: number, text: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_prompt_text", { id, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async togglePromptFavorite(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_prompt_favorite", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除提示词 → 进废纸篓（编号在清理时回收）。
 */
async trashPrompt(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trash_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 第一步：解析 txt，构建预览（不落库）。
 */
async parsePromptTxt(path: string) : Promise<Result<ImportPreview, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("parse_prompt_txt", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 第二步：落库（ctx=generate 时建临时分组）。号池发放与写入同事务。
 */
async commitPromptImport(preview: ImportPreview, ctx: string) : Promise<Result<ImportResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("commit_prompt_import", { preview, ctx }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 保存一份提示词 txt 模板到用户选定位置（E37）。返回保存路径；取消返回 None。
 */
async savePromptTemplate() : Promise<Result<string | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_prompt_template") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 组合展开创建批次，调度器自动开跑。返回批次视图（含任务总数）。
 */
async createBatch(input: CreateBatchInput) : Promise<Result<BatchView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_batch", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 历史单张生成均值秒数（E31 确认摘要 ETA 估算）；无成功历史返回 None。
 */
async estimateTaskSeconds() : Promise<Result<number | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("estimate_task_seconds") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 取消批次剩余排队任务（E03）：删除该批次全部 'q' 态任务，重估归档并补发汇总。
 * 在途（run/retry）任务不受影响，会自行跑完。返回取消数。
 */
async cancelBatchPending(batchId: number) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_batch_pending", { batchId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listBatches() : Promise<Result<BatchView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_batches") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 读取某批次的挂靠与参数快照（E07 再来一批）。只返回未删除的参考图与仍存在的分组，
 * 保证还原到生成页后可直接创建新批次。
 */
async getBatchConfig(batchId: number) : Promise<Result<BatchConfig, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_batch_config", { batchId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 批次备注命名（E10）。空串清除备注。
 */
async renameBatch(batchId: number, note: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_batch", { batchId, note }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pauseQueue() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_queue") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resumeQueue() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_queue") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 在系统文件管理器打开某批次的输出目录（E15）：`outputs/{batch_id}`。
 * 目录不存在（尚无通过作品）时先创建，避免打开失败。
 */
async openBatchOutputDir(batchId: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_batch_output_dir", { batchId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 列出某批次任务，可按 5 视觉组筛选：all/pending/running/failed/review/done。
 */
async listTasks(batchId: number, statusGroup: string | null, page: number | null) : Promise<Result<TaskView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_tasks", { batchId, statusGroup, page }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTask(id: number) : Promise<Result<TaskView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_task", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 手动重试单个失败任务（可携带微调提示词写入快照，R8）。
 */
async retryTask(id: number, editedPrompt: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retry_task", { id, editedPrompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 重试某批次全部失败任务（E06：默认排除违规类 ContentPolicy——原样重试必再违规，
 * 应走「改词重试」E34 单独处理）。
 */
async retryFailedTasks(batchId: number) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retry_failed_tasks", { batchId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除单个任务（「不需要了」）。生成中/重试中的任务不允许删除，避免与在途 worker 竞争；
 * 删除会级联清除 task_attempts（外键 ON DELETE CASCADE）。删除后重估批次归档并补发汇总。
 */
async deleteTask(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_task", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除某批次全部失败任务（批量「不需要了」）。返回删除数。
 */
async deleteFailedTasks(batchId: number) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_failed_tasks", { batchId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 重试全部因中断而失败的任务（error_type=Interrupted）。
 */
async retryInterruptedTasks() : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retry_interrupted_tasks") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 统计当前中断任务数（前端 banner 用）。
 */
async countInterrupted() : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("count_interrupted") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listPendingReview(batchId: number | null) : Promise<Result<ReviewItemView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_pending_review", { batchId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 通过所选：输出原图 + 写作品快照 + 微调写回(R8) + 临时组转正(R7)，单事务。
 */
async acceptTasks(taskIds: number[]) : Promise<Result<AcceptResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("accept_tasks", { taskIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 不通过所选：置 rej + 原图暂存进废纸篓（E02，不立即物理删除）+ 留缩略图，单事务。
 */
async rejectTasks(taskIds: number[]) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reject_tasks", { taskIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listWorks(filter: WorkFilter, page: number | null) : Promise<Result<WorkView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_works", { filter, page }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWork(id: number) : Promise<Result<WorkView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_work", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleWorkFavorite(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_work_favorite", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除作品 → 进废纸篓（记录删除，文件待清理时物理删）。
 */
async trashWork(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trash_work", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 文件是否存在（E21 作品源文件缺失懒检测）。
 */
async fileExists(path: string) : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("file_exists", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 从资产区快照重新导出作品输出文件（E21）：源为 `results/{task_id}.{ext}`。
 * 批次已删除（task_id 为空）或快照已随清理消失时报可读错误。
 */
async reexportWork(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reexport_work", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 批量收藏（E15）。favorite=true 收藏，false 取消。
 */
async setWorksFavorite(ids: number[], favorite: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_works_favorite", { ids, favorite }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 批量删除作品 → 进废纸篓（E15）。默认不物理删除外部输出文件（同 trash_work 决策）。
 */
async trashWorks(ids: number[]) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trash_works", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 批量导出作品到指定文件夹（E15）：复制各作品输出文件（image_path）到目标目录。
 * 返回成功导出数；源文件缺失的项跳过（不计入）。
 */
async exportWorks(ids: number[], destDir: string) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_works", { ids, destDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 各分组产出统计（E25）。按当前 prompts.group_id 归属（提示词移组后随之变化）。
 */
async listGroupStats() : Promise<Result<GroupStat[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_group_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async promptStats(promptId: number) : Promise<Result<PromptStat, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("prompt_stats", { promptId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async productionOverview() : Promise<Result<ProductionOverview, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("production_overview") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listTrash() : Promise<Result<TrashItemView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_trash") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async purgeTrashItems(ids: number[]) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("purge_trash_items", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async purgeAllTrash() : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("purge_all_trash") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async countTrash() : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("count_trash") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 手动/启动检查更新：有新版则后台下载并暂存，emit ready。
 */
async checkUpdateNow() : Promise<Result<string | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_update_now") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 安装已下载的更新并重启（用户确认「重启安装」时调用）。
 */
async installUpdate() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dataDirInfo() : Promise<Result<DataDirInfo, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("data_dir_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 在系统文件管理器中打开数据目录。
 */
async openDataDir() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_data_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 导出备份：选目标 zip → WAL 检查点 → 打包数据目录（排除 logs）。
 * 队列运行中（有 run/retry 任务）拒绝，避免边写边打包出不一致备份。
 * 返回所选路径；用户取消返回 None。
 */
async exportBackup() : Promise<Result<string | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_backup") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPublishSettings() : Promise<Result<PublishSettings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_publish_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePublishSettings(patch: PublishSettingsPatch) : Promise<Result<PublishSettings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_publish_settings", { patch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 选择本机根目录（dialog）；返回所选路径，取消返回 None。
 */
async pickPublishRoot() : Promise<Result<string | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pick_publish_root") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 拓扑 B「同本机」一键：把执行机根路径设为本机根路径。
 */
async useLocalAsExecRoot() : Promise<Result<PublishSettings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("use_local_as_exec_root") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 五平台 `{code, zh}`（前端矩阵/选择器单点数据源）。
 */
async publishPlatforms() : Promise<Result<PlatformInfo[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("publish_platforms") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSkus(filter: SkuFilter) : Promise<Result<SkuView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_skus", { filter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createSku(input: CreateSkuInput) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_sku", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSku(id: number, patch: SkuPatch) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_sku", { id, patch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSkuStatus(id: number, status: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_sku_status", { id, status }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSkuDetail(id: number) : Promise<Result<SkuDetail, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sku_detail", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPublishBadges() : Promise<Result<PublishBadges, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_publish_badges") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listTextItems(skuId: number, kind: string) : Promise<Result<TextItemView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_text_items", { skuId, kind }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addTextItem(input: AddTextItemInput) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_text_item", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateTextItem(id: number, patch: TextItemPatch) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_text_item", { id, patch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTextItemEnabled(id: number, enabled: boolean) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_text_item_enabled", { id, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAssetPacks(skuId: number) : Promise<Result<PackView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_asset_packs", { skuId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 手动导入素材文件（走与收件箱相同的归集/命名管线）。
 */
async importMediaFiles(skuId: number, paths: string[]) : Promise<Result<PackView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_media_files", { skuId, paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 作品库联动：把选中的输出图复制为一个图集包。
 */
async packFromWorks(skuId: number, workIds: number[]) : Promise<Result<PackView | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pack_from_works", { skuId, workIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async retirePack(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retire_pack", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restorePack(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_pack", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除素材包：校验锁定 → 物理删目录 + 删记录。
 */
async deletePack(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_pack", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePack(id: number, patch: PackPatch) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_pack", { id, patch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 手动把 new 包标记为 active（可用）。
 */
async activatePack(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("activate_pack", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 列出收件箱记录；state 为空则全部。
 */
async listInboxItems(filterState: string | null) : Promise<Result<InboxItemView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_inbox_items", { filterState }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 认领：人工指认 SKU 后走正常收录管线。
 */
async claimInboxItem(id: number, skuCode: string) : Promise<Result<IngestOutcome, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("claim_inbox_item", { id, skuCode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 丢弃待认领/失败记录（删记录，文件留原位不动）。
 */
async discardInboxItem(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discard_inbox_item", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 解析失败重试：对原文件重跑收录管线。
 */
async retryInboxItem(id: number) : Promise<Result<IngestOutcome, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retry_inbox_item", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async rescanInbox() : Promise<Result<RescanResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rescan_inbox") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAccounts() : Promise<Result<AccountView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_accounts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createAccount(input: CreateAccountInput) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_account", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateAccount(id: number, patch: AccountPatch) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_account", { id, patch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAccountStatus(id: number, status: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_account_status", { id, status }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
backupProgress: BackupProgress,
batchSummary: BatchSummary,
inboxIngestEvent: InboxIngestEvent,
keyHealth: KeyHealth,
publishBadgesEvent: PublishBadgesEvent,
sheetChangedEvent: SheetChangedEvent,
taskProgress: TaskProgress,
taskStatusChanged: TaskStatusChanged,
updateStateChanged: UpdateStateChanged
}>({
backupProgress: "backup-progress",
batchSummary: "batch-summary",
inboxIngestEvent: "inbox-ingest-event",
keyHealth: "key-health",
publishBadgesEvent: "publish-badges-event",
sheetChangedEvent: "sheet-changed-event",
taskProgress: "task-progress",
taskStatusChanged: "task-status-changed",
updateStateChanged: "update-state-changed"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * 验收结果。
 */
export type AcceptResult = { accepted: number; 
/**
 * 本次因验收通过而转正的临时分组名（前端 toast）
 */
promotedGroups: string[] }
export type AccountPatch = { name: string | null; dailyLimit: number | null; 
/**
 * `Some(None)` = 清除（跟随全局时段模板）；`Some(Some)` = 设置。
 */
slots: string[] | null }
export type AccountView = { id: number; platform: string; platformZh: string; name: string; dailyLimit: number; slots: string[] | null; status: string; createdAt: number }
export type AddApiKeyInput = { alias: string; key: string; baseUrl: string; model: string; concurrencyLimit: number; 
/**
 * 每分钟请求上限（E18）；None/<=0 = 不限速。
 */
rpmLimit: number | null }
export type AddTextItemInput = { skuId: number; kind: string; text: string; platform: string | null }
/**
 * API Key 脱敏视图（Key 本体永不出 Rust）。
 */
export type ApiKeyView = { id: number; name: string; 
/**
 * 脱敏 Key：`****后4位`
 */
maskedKey: string; baseUrl: string; model: string; concurrencyLimit: number; enabled: boolean; 
/**
 * 每分钟请求上限（E18）；None = 不限速。
 */
rpmLimit: number | null; 
/**
 * 是否已被自动熔断（E18）：连续 Auth/欠费失败导致停用，可在设置页恢复。
 */
circuitBroken: boolean; 
/**
 * 近 50 次成功率（0.0–1.0）
 */
successRate: number; 
/**
 * 成功率样本量
 */
sampleCount: number; 
/**
 * 当前占用并发（运行时；M2 引擎接入后填充，M1 恒为 0）
 */
usedConcurrency: number }
/**
 * 应用级错误。`type` 字段作为前端可判别的分类标签。
 */
export type AppError = 
/**
 * 数据库 / 持久化失败。
 */
{ type: "Database"; message: string } | 
/**
 * 文件系统 / IO 失败。
 */
{ type: "Io"; message: string } | 
/**
 * 输入参数非法（前端应在提交前拦截，此为兜底）。
 */
{ type: "InvalidInput"; message: string } | 
/**
 * 系统钥匙串（Keychain / 凭据管理器）访问失败。
 */
{ type: "Keyring"; message: string } | 
/**
 * 其它未分类错误。
 */
{ type: "Internal"; message: string }
/**
 * `backup://progress`：导出进度（前端进度条）。
 */
export type BackupProgress = { done: number; total: number; 
/**
 * running / done / error
 */
phase: string }
/**
 * 批次配置快照（E07「按此配置再来一批」）：还原生成页挂靠与参数。
 */
export type BatchConfig = { 
/**
 * 参考图 → 提示词组挂靠（仅保留当前仍存在的参考图与分组）。
 */
refs: RefMappingInput2[]; paramsJson: string }
/**
 * `batch://summary`（250ms 节流）
 */
export type BatchSummary = { batchId: number; counts: SummaryCounts; activeConcurrency: number; paused: boolean; 
/**
 * 自动暂停原因（E05 全局熔断）；None = 非自动暂停或运行中。
 */
autoPauseReason: string | null }
export type BatchView = { id: number; createdAt: number; status: string; taskCount: number; 
/**
 * 批次生效的生成参数快照（E16 / D1），任务页可回查。
 */
paramsJson: string; 
/**
 * 批次备注名（E10）；None = 未命名。
 */
note: string | null; 
/**
 * 首张产出缩略图（E10 批次切换器预览）。
 */
firstThumbPath: string | null; 
/**
 * 实际请求次数（含重试，E15）：该批次全部任务的 task_attempts 计数。
 */
requestCount: number }
export type CreateAccountInput = { platform: string; name: string; dailyLimit: number | null; slots: string[] | null }
export type CreateBatchInput = { refs: RefMappingInput[]; paramsJson: string; 
/**
 * 抽卡次数 k（E17 / D2）：每个组合独立生成 k 次。默认 1，后端夹取 1..=5。
 */
draws: number }
/**
 * 新建 SKU 输入。
 */
export type CreateSkuInput = { code: string; styleName: string; productName: string | null; tier: string | null; topics: string[] | null; platforms: string[] | null; note: string | null }
/**
 * 数据目录信息（E19：暴露落盘位置）。
 */
export type DataDirInfo = { root: string; dbPath: string }
/**
 * 六类错误（落 `tasks.error_type` / `task_attempts.error_type`）。
 */
export type ErrorType = "Timeout" | "RateLimited" | "ContentPolicy" | "Auth" | "Interrupted" | "Other"
/**
 * 前端未捕获错误载荷。经 ErrorBoundary / window.onerror 采集后转发到此。
 */
export type FrontendErrorPayload = { 
/**
 * 错误消息。
 */
message: string; 
/**
 * 调用栈（可选）。
 */
stack: string | null; 
/**
 * 来源标识（组件 / 路由）。
 */
source: string | null; 
/**
 * 关联任务 ID（若发生在任务上下文），用于全链路贯穿。
 */
taskId: string | null }
/**
 * 单个分组的产出统计（E25 分组卡片合格率）。
 */
export type GroupStat = { groupId: number; 
/**
 * 已产出图的去重组合数（分母）。
 */
combos: number; 
/**
 * 通过图覆盖的去重组合数（分子）。
 */
passed: number; 
/**
 * 累计通过作品数。
 */
works: number }
/**
 * 分组视图（生成页 / 提示词库列表）。
 */
export type GroupView = { id: number; name: string; prefix: string; scene: string; isTemp: boolean; count: number; 
/**
 * 分组绑定的标签（E20 按标签筛选）。
 */
tags: string[] }
/**
 * 一条发布历史（读台账）。
 */
export type HistoryItem = { date: string; platform: string; taskCode: string; url: string | null; publishedAt: number }
/**
 * 导入预览（parse 阶段产物，不落库）。
 */
export type ImportPreview = { encoding: string; groups: ImportPreviewGroup[]; total: number; 
/**
 * 行号级诊断（E37），非致命，仅提示。
 */
warnings: ImportWarning[] }
export type ImportPreviewGroup = { name: string; prefix: string; scene: string; tags: string[]; count: number; 
/**
 * 预分配编号区间预览，如 "DZ-0001 ~ DZ-0024"（忽略回收池，仅供参考）
 */
codeRange: string; isNewGroup: boolean; 
/**
 * 提示词（正文 + 可选小标题；commit 阶段回传落库）
 */
prompts: ImportPreviewPrompt[] }
/**
 * 导入预览中的单条提示词（正文 + 可选小标题）。
 */
export type ImportPreviewPrompt = { title: string | null; text: string }
export type ImportResult = { groupIds: number[]; inserted: number; 
/**
 * 是否新建了临时分组（ctx=generate）
 */
temp: boolean }
/**
 * 导入诊断（E37：缺分组标记 / 悬空小标题等，含行号）。
 */
export type ImportWarning = { line: number; message: string }
/**
 * `publish://inbox-ingest`：单文件收录结果（前端 toast + 列表刷新）。
 */
export type InboxIngestEvent = { 
/**
 * 收录文件名（末段）。
 */
fileName: string; outcome: IngestOutcome }
export type InboxItemView = { id: number; fileRel: string; 
/**
 * 文件名（末段，UI 展示）。
 */
fileName: string; kind: string | null; skuCode: string | null; state: string; 
/**
 * 收录报告 / 失败原因摘要。
 */
detail: string | null; createdAt: number }
/**
 * 单文件收录结果（供事件与报告使用）。camelCase 字段名个别指定（specta 不识别 rename_all_fields）。
 */
export type IngestOutcome = 
/**
 * 成功入库并归档。
 */
{ state: "ingested"; skuCode: string; kind: string; titles: number; bodies: number; topicsAdopted: string[]; topicDiff: string | null } | 
/**
 * 识别不出已知 SKU，待认领。
 */
{ state: "unclaimed"; skuCode: string | null } | 
/**
 * 解析失败，待人工确认。
 */
{ state: "failed"; reason: string }
/**
 * `keys://health`
 */
export type KeyHealth = { keyId: number; state: KeyState; usedConcurrency: number; successRate: number }
/**
 * Key 健康状态。
 */
export type KeyState = "ok" | "limited" | "auth_failed" | "disabled"
export type PackFileView = { name: string; origName: string; bytes: number }
export type PackPatch = { note: string | null; 
/**
 * `Some(None)` = 清除封面；`Some(Some)` = 设为该包内文件名。
 */
cover: string | null }
export type PackView = { id: number; skuId: number; kind: string; dirRel: string; files: PackFileView[]; cover: string | null; 
/**
 * 存储态：new|active|retired。
 */
lifecycle: string; 
/**
 * 派生态：new|active|exhausted|retired。
 */
derived: string; 
/**
 * 回可用日期（exhausted 时的最早解冻 Unix 秒）。
 */
availableAt: number | null; 
/**
 * 被未关闭任务单引用（锁定）。
 */
locked: boolean; source: string; note: string; fileCount: number; createdAt: number; updatedAt: number }
export type Phase = "queued" | "requestStarted" | "generating" | "downloading" | "saved"
/**
 * 平台标签信息（暴露给前端做矩阵/选择器渲染，避免前端重复中文映射）。
 */
export type PlatformInfo = { code: string; zh: string }
/**
 * 平台矩阵（全局启用开关）。字段即五平台 code。
 */
export type PlatformMatrix = { douyin: boolean; xhs: boolean; kuaishou: boolean; shipinhao: boolean; bilibili: boolean }
/**
 * 生产总览（E25 生成页顶部条）：今日生成/通过/请求。
 */
export type ProductionOverview = { 
/**
 * 今日成功产出的图片数（task_attempts.outcome='success'）。
 */
generatedToday: number; 
/**
 * 今日验收通过的作品数。
 */
acceptedToday: number; 
/**
 * 今日请求次数（含重试，全部 task_attempts）。
 */
requestsToday: number }
/**
 * 单条提示词的产出统计（E25 提示词详情）。
 */
export type PromptStat = { works: number; combos: number; passed: number }
/**
 * 提示词视图（编号网格 / 详情）。
 */
export type PromptView = { id: number; groupId: number; code: string; title: string | null; text: string; favorite: boolean; edited: boolean }
/**
 * 发布模块导航徽章计数（资产库 = 待认领 + 预警；发布计划 = 待确认任务单 + 待核对）。
 */
export type PublishBadges = { 
/**
 * 待认领 + 解析失败。
 */
unclaimed: number; 
/**
 * 余量预警 SKU 数。
 */
warn: number; 
/**
 * 待确认任务单数（P2 起）。
 */
pendingSheets: number; 
/**
 * 待核对数（P3 起）。
 */
pendingReconcile: number }
/**
 * `publish://badges`：资产库徽章（待认领 + 预警）、发布计划徽章（待确认 + 待核对）。
 */
export type PublishBadgesEvent = { unclaimed: number; warn: number; pendingSheets: number; pendingReconcile: number }
/**
 * 发布与同步设置。
 */
export type PublishSettings = { 
/**
 * 本机根目录（空 = 未配置）。
 */
rootLocal?: string; 
/**
 * 执行机根目录（空 = 未配置；同机模式一键同本机）。
 */
rootExec?: string; 
/**
 * 执行机路径风格（windows|unix）。
 */
pathStyle?: string; 
/**
 * 查重窗口天数。
 */
dedupDays?: number; 
/**
 * 回执超时小时数。
 */
receiptTimeoutHours?: number; 
/**
 * 每日生成时间（HH:MM）。
 */
autogenTime?: string; 
/**
 * 素材余量预警阈值。
 */
warnMaterial?: number; 
/**
 * 标题余量预警阈值。
 */
warnTitle?: number; 
/**
 * 正文余量预警阈值（仅对有图集包的 SKU 生效）。
 */
warnBody?: number; 
/**
 * 账号默认日上限。
 */
accountDailyLimitDefault?: number; 
/**
 * 同平台多账号最小间隔（分钟）。
 */
minGapMinutes?: number; platformMatrix?: PlatformMatrix; tierRules?: TierRules; 
/**
 * 时段模板（`HH:MM-HH:MM`）。
 */
timeSlots?: string[] }
/**
 * 设置补丁（部分更新）。
 */
export type PublishSettingsPatch = { rootLocal: string | null; rootExec: string | null; pathStyle: string | null; dedupDays: number | null; receiptTimeoutHours: number | null; autogenTime: string | null; warnMaterial: number | null; warnTitle: number | null; warnBody: number | null; accountDailyLimitDefault: number | null; minGapMinutes: number | null; platformMatrix: PlatformMatrix | null; tierRules: TierRules | null; timeSlots: string[] | null }
/**
 * 参考图详情（含使用统计）。
 */
export type RefImageDetail = { id: number; name: string; groupId: number | null; filePath: string; thumbPath: string; width: number; height: number; usedCount: number; worksCount: number }
export type RefImageView = { id: number; name: string; groupId: number | null; filePath: string; thumbPath: string; width: number; height: number; 
/**
 * 最近一次挂靠的提示词组（E32 挂靠记忆）；生成页据此预填挂靠。
 */
lastGroupId: number | null }
export type RefMappingInput = { refImageId: number; promptGroupId: number }
/**
 * 挂靠输出项（与 RefMappingInput 同形，但用于序列化返回）。
 */
export type RefMappingInput2 = { refImageId: number; promptGroupId: number }
/**
 * 导入前重复扫描（E30b）：按内容 hash 比对已有库 + 本次列表内，标注重复项。
 */
export type RefScanItem = { path: string; name: string; duplicate: boolean; 
/**
 * 与之重复的已有图名（库内）或本次靠前的文件名。
 */
dupOf: string | null }
/**
 * 手动全量扫描收件箱。返回本次收录/待认领/失败计数。
 */
export type RescanResult = { ingested: number; unclaimed: number; failed: number }
/**
 * 待验收项视图。
 */
export type ReviewItemView = { id: number; batchId: number; refName: string; promptCode: string; groupName: string; keyAlias: string | null; resultImagePath: string | null; resultThumbPath: string | null; promptText: string; 
/**
 * 参考图缩略图/原图（E08 大图对比）。
 */
refThumbPath: string | null; refImagePath: string | null }
/**
 * 应用设置（单行 JSON 持久化）。
 */
export type Settings = { 
/**
 * 调度策略："round_robin" | "success_rate"
 */
scheduleStrategy: string; 
/**
 * 失败重试次数（0–3）
 */
retryCount: number; 
/**
 * 输出根目录
 */
outputDir: string; 
/**
 * 动效偏好："standard" | "reduced"
 */
motion: string; 
/**
 * 队列暂停态
 */
paused: boolean; 
/**
 * 全局熔断阈值（E05）：跨 Key 连续失败达此数自动暂停队列；0 = 关闭。
 */
globalFailThreshold?: number; 
/**
 * 废纸篓保留天数（E40 / D3）：删除项保留满此天数后启动时自动物理清理；0 = 不自动清理。
 */
trashRetentionDays?: number; 
/**
 * 归档批次保留天数（E22 / D3）：批次归档满此天数后启动时自动删除（作品不受影响）；0 = 不自动删除。
 */
batchRetentionDays?: number; 
/**
 * 首次使用引导是否已完成（E13）：四步齐备后置 true，引导永久消失。
 */
onboarded?: boolean }
/**
 * 设置补丁（部分更新）。
 */
export type SettingsPatch = { scheduleStrategy: string | null; retryCount: number | null; outputDir: string | null; motion: string | null; paused: boolean | null; globalFailThreshold: number | null; trashRetentionDays: number | null; batchRetentionDays: number | null; onboarded: boolean | null }
/**
 * `publish://sheet-changed`：任务单状态/行状态变化（P2/P3 工作台与看板刷新）。
 */
export type SheetChangedEvent = { sheetId: number; date: string; status: string; 
/**
 * 汇总计数（待执行/已发布/失败/疑似/已取消）。
 */
pending: number; published: number; failed: number; suspect: number; canceled: number }
/**
 * SKU 详情：档案视图 + 发布历史（池明细由 assets/texts 域命令单独取）。
 */
export type SkuDetail = { sku: SkuView; history: HistoryItem[] }
/**
 * 列表过滤条件。
 */
export type SkuFilter = { tier: string | null; warnOnly: boolean | null; status: string | null; query: string | null }
/**
 * 编辑补丁。
 */
export type SkuPatch = { styleName: string | null; productName: string | null; tier: string | null; topics: string[] | null; 
/**
 * `Some(None)` = 清除覆盖（跟随全局矩阵）；`Some(Some(..))` = 设置覆盖。
 */
platforms: string[] | null; note: string | null }
/**
 * SKU 列表/详情视图。
 */
export type SkuView = { id: number; code: string; styleName: string; productName: string; tier: string; topics: string[]; 
/**
 * 平台覆盖（NULL=跟随全局矩阵）。
 */
platforms: string[] | null; status: string; isGeneral: boolean; note: string; materialCount: number; titleCount: number; bodyCount: number; hasGallery: boolean; lastPublished: number | null; 
/**
 * 各池预警（低于阈值）。
 */
warnMaterial: boolean; warnTitle: boolean; warnBody: boolean; 
/**
 * 任一池预警。
 */
warn: boolean }
/**
 * 5 视觉组计数。
 */
export type SummaryCounts = { 
/**
 * 待处理 q
 */
pending: number; 
/**
 * 生成中 run+retry
 */
running: number; 
/**
 * 异常 fail
 */
failed: number; 
/**
 * 待验收 rev
 */
review: number; 
/**
 * 已通过 pass
 */
passed: number; 
/**
 * 未通过 rej
 */
rejected: number; total: number }
/**
 * `task://progress`（250ms 节流）
 */
export type TaskProgress = { taskId: number; pct: number; phase: Phase }
export type TaskStatus = 
/**
 * 待生成
 */
"q" | 
/**
 * 生成中
 */
"run" | 
/**
 * 重试中（退避/排队等待再次生成）
 */
"retry" | 
/**
 * 成功（即待验收）
 */
"rev" | 
/**
 * 已通过
 */
"pass" | 
/**
 * 未通过
 */
"rej" | 
/**
 * 失败（可手动重试的终态）
 */
"fail"
/**
 * `task://status-changed`
 */
export type TaskStatusChanged = { taskId: number; batchId: number; status: TaskStatus; errorType: ErrorType | null; errorMessage: string | null; retryCount: number; apiKeyId: number | null }
/**
 * 任务视图（含参考图名/提示词编号/分组名/Key 别名，供任务表直接渲染）。
 */
export type TaskView = { id: number; batchId: number; status: string; refImageId: number; refName: string; promptId: number; promptCode: string; promptTitle: string | null; groupName: string; apiKeyId: number | null; keyAlias: string | null; errorType: string | null; errorMessage: string | null; retryCount: number; resultThumbPath: string | null; promptTextSnapshot: string }
export type TextItemPatch = { text: string | null; platform: string | null }
export type TextItemView = { id: number; skuId: number; kind: string; text: string; 
/**
 * 平台标签 code（douyin…|general）。
 */
platform: string; 
/**
 * 平台中文名（UI 展示）。
 */
platformZh: string; source: string; enabled: boolean; useCount: number; createdAt: number }
/**
 * 分层频率规则（扁平化 §3 的 `{hot:{daily},warm:{weekly},cold:{weeklyRotate}}`）。
 */
export type TierRules = { 
/**
 * 热款：每天次数（× 平台集）。
 */
hotDaily: number; 
/**
 * 温款：每周次数。
 */
warmWeekly: number; 
/**
 * 冷款：轮播池每周轮出个数。
 */
coldWeeklyRotate: number }
export type TrashItemView = { id: number; entityType: string; code: string | null; title: string | null; refName: string | null; thumbPath: string | null; 
/**
 * 未通过任务的原图路径（E02：原图暂存至清理前可查看）。仅 task 类有值。
 */
imagePath: string | null; promptText: string | null; sourceLabel: string; deletedAt: number }
export type UpdateApiKeyPatch = { name: string | null; baseUrl: string | null; model: string | null; concurrencyLimit: number | null; 
/**
 * None = 不改；Some(n>0) = 设为 n；Some(n<=0) = 清除限速（不限）。
 */
rpmLimit: number | null; 
/**
 * 轮换密钥：None/空串 = 保持原 Key 不变；Some(非空) = 覆写钥匙串中的密钥。
 * 编辑弹窗里留空即不改 Key，只改元数据。
 */
key: string | null }
/**
 * `update://state`
 */
export type UpdateStateChanged = { 
/**
 * checking / downloading / ready / uptodate / error
 */
state: string; version: string | null }
export type WorkFilter = { groupId: number | null; favoriteOnly: boolean }
export type WorkView = { id: number; promptCode: string; groupName: string; refName: string; batchId: number | null; favorite: number; acceptedAt: number; imagePath: string; thumbPath: string; promptText: string; 
/**
 * 复刻/再生成所需的原始关联（E33）；批次删除后 task_id 可能为空。
 */
refImageId: number | null; groupId: number | null; taskId: number | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
