#!/usr/bin/env bash
# ============================================================================
# guardrails.sh —— 架构铁律的机器化检查（执行计划 §1.2）。
# CLAUDE.md 里每条「禁止」在这里都有对应检查；违反即非零退出，CI 变红。
# 用法：bash scripts/guardrails.sh
# ============================================================================
set -uo pipefail
cd "$(dirname "$0")/.."

fail=0
report() { echo "  ✗ $1"; fail=1; }

# grep 包装：命中即返回内容（-n 带行号）；忽略不存在目录。
scan() { grep -rnE "$1" $2 2>/dev/null; }

echo "▶ guardrails: 架构铁律检查"

# ---------------------------------------------------------------------------
# 1) invoke( / listen( 只允许出现在 src/lib/ipc/（前端只经 IPC 封装出入）
# ---------------------------------------------------------------------------
echo "· [1] invoke/listen 仅限 src/lib/ipc/"
hits=$(grep -rnE '\b(invoke|listen)\(' src --include='*.ts' --include='*.tsx' 2>/dev/null \
  | grep -v '^src/lib/ipc/' || true)
if [ -n "$hits" ]; then
  report "invoke(/listen( 出现在 lib/ipc 之外："
  echo "$hits" | sed 's/^/      /'
fi

# ---------------------------------------------------------------------------
# 2) oklch( 硬编码只允许出现在 src/styles/globals.css（token 单一来源）
# ---------------------------------------------------------------------------
echo "· [2] oklch( 仅限 globals.css"
hits=$(grep -rnE 'oklch\(' src --include='*.ts' --include='*.tsx' --include='*.css' 2>/dev/null \
  | grep -v '^src/styles/globals.css' || true)
if [ -n "$hits" ]; then
  report "oklch( 硬编码出现在 globals.css 之外："
  echo "$hits" | sed 's/^/      /'
fi

# ---------------------------------------------------------------------------
# 3) 禁 console.log（前端一律走 reportFrontendError / tracing）
# ---------------------------------------------------------------------------
echo "· [3] 禁 console.log"
hits=$(grep -rnE 'console\.log\(' src --include='*.ts' --include='*.tsx' 2>/dev/null || true)
if [ -n "$hits" ]; then
  report "出现 console.log："
  echo "$hits" | sed 's/^/      /'
fi

# ---------------------------------------------------------------------------
# 4) 禁无说明的 #[allow(...)]（同行或上一行须有 // 注释说明理由）
# ---------------------------------------------------------------------------
echo "· [4] #[allow(...)] 必须有说明注释"
while IFS= read -r line; do
  [ -z "$line" ] && continue
  file="${line%%:*}"; rest="${line#*:}"; lineno="${rest%%:*}"
  # 同行是否含注释
  if echo "$line" | grep -qE '//'; then continue; fi
  # 上一行是否含注释
  prev=$(sed -n "$((lineno-1))p" "$file" 2>/dev/null)
  if echo "$prev" | grep -qE '//'; then continue; fi
  report "无说明的 #[allow]: $file:$lineno"
done < <(grep -rnE '#\[allow\(' src-tauri/src 2>/dev/null || true)

# ---------------------------------------------------------------------------
# 5) 脱敏：Rust 代码中不得出现疑似 API Key 明文（sk-xxxx…）
# ---------------------------------------------------------------------------
echo "· [5] Rust 源码无疑似 Key 明文（sk-…）"
hits=$(grep -rnE 'sk-[A-Za-z0-9_-]{6,}' src-tauri/src 2>/dev/null || true)
if [ -n "$hits" ]; then
  report "疑似 API Key 明文出现在 Rust 源码："
  echo "$hits" | sed 's/^/      /'
fi

# ---------------------------------------------------------------------------
# 6) bindings.ts 禁手改：必须带 tauri-specta 生成头
# ---------------------------------------------------------------------------
echo "· [6] bindings.ts 为生成文件"
if [ -f src/lib/ipc/bindings.ts ]; then
  if ! head -3 src/lib/ipc/bindings.ts | grep -q 'generated by'; then
    report "bindings.ts 缺少生成头（疑似手改）"
  fi
fi

if [ "$fail" -eq 0 ]; then
  echo "✓ guardrails 全部通过"
else
  echo "✗ guardrails 存在违规，见上方"
fi
exit "$fail"
